### ISSUE TITLE
CustomUrlProvider

### ISSUE THREAD

**Issue by v-jacai** [GitTools/GitLink#142]
I am trying CustomUrlProvider, here is my RAWURL:
RAWURL=**http://tfshost:8080/tfs/Jupiter/1c144528-6776-430b-a424-59e93c6aa3b3/_api/_versioncontrol/itemContent?**repositoryId=0bc9fd51-425e-4d98-bc7f-fbe32b35a3b1&version=GC45f57126c406870d4eae7331e7b50d9bda3898a2&contentOnly=true&__v=5&path=%var2% 

When I debugging into pdb file, it **cannot** download the file to my local machine. It will create folder like tfs\Jupiter\1c144528-6776-430b-a424-59e93c6aa3b3\_api\_versioncontrol\itemContent, it will stop at the itemContent node, I think it's due to I have one question mark at here. Any idea how to fix it?

I looked into the UnitTest, you have one CustomURL demo. 
https://bitbucket.intra.company.com/projects/aaa/repos/a/browse/{filename}?at={revision}&raw

However I think it works fine due to it have {filename} folder before the question mark.

**Comment by GeertvanHorrik** [comment]
The double ** could confuse because it's used as a separator in the SRCSRV file. Is it something you did yourself or...?

**Comment by v-jacai** [comment]
Thanks to reply me! 
I was mean to highlight http://tfshost:8080/tfs/Jupiter/1c144528-6776-430b-a424-59e93c6aa3b3/_api/_versioncontrol/itemContent? part. You can ignore the double **

**Comment by mesheets** [comment]
Based on research I have done, this is actually an internal issue somewhere within the Microsoft portion of the PDB-supporting tooling.  For whatever reason, URLs needing to make use of a query string (i.e. the question mark and anything following that within a URL) do not work with Microsoft's tooling.  I tried to submit an MSDN support ticket on this, but the response I received back from Microsoft was that that tooling was "unsupported."  (To be more specific, the problem perhaps might be within SrcTool.exe, but I can't say for certain.)

If using the core Git implementation with GitWeb, there is an option to incorporate PATH_INFO support (c.f. https://git-scm.com/docs/gitweb).  At a high level, this essentially sets up the query string parameters as components of the URL path instead (eliminating the query string portion of the URL).

As part of the process of trying to isolate and pinpoint this issue, I had two Git repositories setup—one using the default query string URLs and another using path-based URL.  The apart from the custom URL passed to GitLink, the usage of GitLink in the build processes for each of these two different Git repositories was otherwise identical.  Symbol debugging worked against the Git repository that used the path-based URLs but failed against the Git repository that used the URL query strings.


Possible workaround for you?
I see the :8080 port number and /tfs application root in the URL, and so speculating that you are perhaps using TFS as your version control provider, I might suggest trying the "Index Sources and Publish Symbols" build step (instead of GitLink) if you are using Team Build vNext with the "Scriptable" capabilities.  Of course, this is also publishes the symbols, so if you are not doing symbol publishing, that might not be an option.  (At least in my testing, as long as I used the Microsoft tooling to index TFS-hosted Git repositories, everything seemed to work as expected; however, there were cases where I wanted these symbol capabilities to work with non-TFS-hosted Git repositories.)

Aside:
If wanting to publish symbols but if not using a TFS-based Git repository, you can still leverage both GitLink (for indexing) and the aforementioned "Index Sources and Publish Symbols" build step (for publishing) by setting up the build steps as follows:
 * Compile sources
 * Run GitLink
 * "Index Sources and Publish Symbols"
    - IMPORTANT: Since using GitLink, once must expand the "Advanced" options for this step and check the "Skip indexing" option

**Comment by bacar** [comment]
I'm somewhat confused -- the custom URL example in the readme contains an URL with query params. Does the example it work, or not?

**Comment by mesheets** [comment]
At least when debugging in Visual Studio, I was never able to get it working with query parameters.  I even went to the extent of setting up a test with two environments that were essentially identical except for how the URL was formed.  The URL with query string parameters always failed; the URL in the PATH_INFO format succeeded.

I even tried engaging Microsoft, as the problem appears to be in how their tooling handles URLs, but the response I received was that this particular debug tooling was "unsupported."

**Comment by GeertvanHorrik** [comment]
Hopefully the new pdb format will have improved support for this (portable pdbs).

**Comment by bacar** [comment]
OK, so am I right in understanding that the example custom URL given in the readme:

    GitLink.exe <pdbfile> -u "https://host/projects/catel/repos/catel/browse/{filename}?at={revision}&raw"

...has never worked and will not work? If so, could I suggest scrapping that example for a better one?

**Comment by ctaggart** [comment]
@bacar, source server support has a lot of limitations. [Special characters are not supported](https://github.com/ctaggart/SourceLink/issues/94) in URLs for source server support. They are supported for the new source link support. If you can use Visual Studio 2017, perhaps you can have a look at https://github.com/ctaggart/SourceLink. GitLink authors have contributed to the new version 2 of it. Be aware that there are some [known issues](https://github.com/ctaggart/SourceLink#known-issues), but they have a much better chance of being resolved.

**Comment by Liryna** [comment]
Well @bacar you are right 😢 Looking at the readme I tried to feet Gitlab raw http url request:
`http://localserver/org/project/raw/{revision}/{filename}?private_token=MY_TOKEN`
But could not make it work. Looked at the url in the pdb, it is a valid url with all correct files.
```
VERSION=2
SRCSRV: variables ------------------------------------------
RAWURL=http://localserver/org/project/raw/07da5gc8e5e9517c7bd97be33879368d949319e7/%var2%?private_token=MY_TOKEN
SRCSRVVERCTRL=http
SRCSRVTRG=%RAWURL%
```
Here is VS 2017 logs:
```
Searching for documents embedded in the symbol file.
An embedded document was not found.
Looking for source using source server...
The debugger will ask the user to find the file
```
Any on succeeding to find a work around on this ?

****edit: done with a nginx proxy pass 👍 like @ctaggart  linked the `?` char is an issue****

**Comment by GeertvanHorrik** [comment]
Thanks for the update. Will close this ticket.
