### ISSUE TITLE
Fix deployment to chocolatey & nuget

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitLink#143]
I've created the environments in AppVeyor, but it looks like the versioning for nuspec is still 1.0.0 (and not respecting the build version).

/cc @AArnott & @gep13 : what should we do to make the nuspec get the right version number as well?

**Comment by AArnott** [comment]
I agree that issue needs to be fixed, of course. While we were on NB.GV it was working, but I'm not familiar enough with GitVersion to know how to use that to fix this problem.

**Comment by GeertvanHorrik** [comment]
@AArnott I see some keys like $GitCommitIdShort$ in GitLink.NuGet.nuproj. Those seem to be variables, but not sure where they are coming from. I checked out the docs for nuproj, but couldn't find anything about variable replacement. Is this a NB.GV feature or a nuproj feature?

**Comment by AArnott** [comment]
The $Macro$ syntax is a nuspec feature. And [NB.GV specially checks for NuProj projects](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/Nerdbank.GitVersioning.NuGet/build/NerdBank.GitVersioning.targets#L165) and adds a couple macro definitions to it so that they automatically expand.
So in a GitVersion world, you'd need to write the code that obtains the git version information and passes it to `nuget pack -Properties x=y`

**Comment by GeertvanHorrik** [comment]
3.0.0-alpha.85.build.67 has just been released to chocolatey & nuget.

**Comment by AArnott** [comment]
Good news!

I see GitLink 3.0.0-unstable0085, which I take to be the version you published. Not sure how the two version spec's align.
