### ISSUE TITLE
Provide pdb folder as path

### ISSUE THREAD

**Issue by Liryna** [GitTools/GitLink#191]
### Feature description
I am using GitLink for a C++ of 100 > libraries. Therefore, using `-a` option that sometimes takes on each library.
I was looking to improve the workflow by allowing GitLink to take a folder and handle all the pdb in it.
How could this can be integrated ?
I thought about simply adding a folder listing here but I guess that the wrong way since the file listing is later.
https://github.com/GitTools/GitLink/blob/develop/src/GitLink/Program.cs#L73

**Comment by GeertvanHorrik** [comment]
At first thought, I think it might work to just loop the directories. We could even make an overload called `Linker.LinkDirectory` method and pass in the pdb files one by one. The pdb files should all go good because for each pdb file, they should be part of the same solution thus the same repository.

But I think the best way would be to use msbuild integration where it automatically takes care of it *per library*, but I can imagine that for 100 libs, it's faster to run it all at once.

**Comment by Liryna** [comment]
Hi @GeertvanHorrik ,

Thank you for the guide. I have created a PR with the changes https://github.com/GitTools/GitLink/pull/193
I have also added cache source files for `-a` option. Calling `GetSourceFilesFromDepot` take 80% of the time on my side. This is extremely helpful when running on 100 pdb and 1000 source files 👍

**Comment by GeertvanHorrik** [comment]
Assuming this can be closed since the PR has been accepted & merged. If not, feel free to re-open.
