### ISSUE TITLE
how to verify gitlink worked

### ISSUE THREAD

**Issue by neutmute** [GitTools/GitLink#69]
Hi there - I've run gitlink against my pdb's for a bitbucket repo but VS2015 still acts as if the sources files are on a local drive where the binaries were compiled. I've set the VS2015 Debugging, Symbols options as suggested.

Is there a way to verify the PDB's have been updated? I tried using [dia2dump](http://www.lionhack.com/2014/01/14/advanced-dotnet-debugging-pdbs-and-symbols/) and can see local paths - not bitbucket paths in the output. I don't know if this is a valid verification though

any tips?

**Comment by GeertvanHorrik** [comment]
What it does is redirect the files if they cannot be found on your local machine. Since you can find them on your local machine (probably testing on the same machine that built the assemblies), you need to:

1. Temporarily rename the original directory so it cannot find the files
2. Try on a different machine (that does not have the same files in the same place!)

**Comment by neutmute** [comment]
I opened the pdb in notepad++ and worked out the error by viewing the `srcsrv` text. thanks for the tips.
