### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by Ashtonian** [GitTools/GitLink#88]
I'm just a bit confused with how to use the tooling exactly?

Is the Nuget Package or the CLI the preferred way of using this tool or do I need both?
How does it play with the jetbrains decompiler/toolset? 
How do you actually use the nuget package - the gif just has the source code running and then you jump in the code with what? 

Sorry if I'm missing something but the documentation is kind of jumpy on getting started and seems like it has a lot more configurations options then the nuget package exposes.

**Comment by GeertvanHorrik** [comment]
See readme.

**Comment by Ashtonian** [comment]
updated issue with some detail - sorry for the empty issue - I hit enter too soon.

**Comment by GeertvanHorrik** [comment]
1. You should use the CLI, unless you want to write some automation tool yourself. NuGet is just a way to distribute the CLI
2. Not sure, but if JetBrains supports source servers, this should work out of the box. Even better, they shouldn't have to decompiler because they can retrieve the source files directly (but again, only if they support it).
3. Best is to use the chocolatey package for now. There is another issue #87 to put this into the tools instead of the lib folder of the nuget package.

**Comment by Ashtonian** [comment]
That makes a lot more sense ! thank you.
